# Generated by Codex on 2026-06-24

import uuid

import django.db.models.deletion
from django.db import migrations, models


def attach_legacy_plans(apps, schema_editor):
    PaymentRequest = apps.get_model("payments", "PaymentRequest")
    SubscriptionPlan = apps.get_model("payments", "SubscriptionPlan")

    for payment in PaymentRequest.objects.filter(plan__isnull=True):
        base_name = f"Legacy {payment.reference}"[:90] or "Legacy Plan"
        name = base_name
        index = 1
        while SubscriptionPlan.objects.filter(partner=payment.partner, name=name).exists():
            suffix = f" {index}"
            name = f"{base_name[:100 - len(suffix)]}{suffix}"
            index += 1

        plan = SubscriptionPlan.objects.create(
            partner=payment.partner,
            name=name,
            amount=payment.amount,
            period="legacy",
            is_active=True,
        )
        payment.plan = plan
        payment.save(update_fields=["plan"])


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="payments.merchantpartner",
                    ),
                ),
            ],
            options={
                "unique_together": {("partner", "name")},
            },
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.subscriptionplan",
            ),
        ),
        migrations.RunPython(attach_legacy_plans, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="paymentrequest",
            name="amount",
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.subscriptionplan",
            ),
        ),
    ]
