# Generated by Django 6.0.3 on 2026-03-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_banque', models.CharField(max_length=100)),
                ('type_compte', models.CharField(choices=[('bancaire', 'Compte Bancaire'), ('ccp', 'CCP / Poste'), ('mobile', 'Paiement Mobile'), ('autre', 'Autre')], default='bancaire', max_length=20)),
                ('numero_compte', models.CharField(max_length=50)),
                ('api_token', models.TextField(blank=True, help_text="Token d'intégration API bancaire")),
                ('is_actif', models.BooleanField(default=True)),
                ('commercant', models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_externes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Externe',
                'db_table': 'comptes_externes',
                'unique_together': {('commercant', 'numero_compte')},
            },
        ),
    ]
