# Generated by Django 6.0.3 on 2026-03-27 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '__first__'),
        ('wallets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type', models.CharField(choices=[('interne', 'Transfert Interne'), ('externe', 'Paiement Externe'), ('chargement', 'Chargement Wallet')], db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('commercant', models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('compte_externe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='comptes.compteexterne')),
                ('wallet_expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_emises', to='wallets.wallet')),
                ('wallet_recepteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_recues', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
