# Generated by Django 6.0.3 on 2026-06-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0002_cascade_on_delete_user_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commercant',
            field=models.ForeignKey(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_emises', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_recues', to='wallets.wallet'),
        ),
    ]
