# Generated by Django 6.0.3 on 2026-06-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_cascade_on_delete_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('interne', 'Transfert Interne'), ('externe', 'Paiement Externe'), ('chargement', 'Chargement Wallet'), ('interop_received', 'Reception interop')], db_index=True, max_length=20),
        ),
    ]
