# Generated by Django 6.0.3 on 2026-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20),
        ),
    ]
