# Generated by Django 6.0.3 on 2026-03-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gratuit', 'Gratuit'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('nb_comptes_max', models.IntegerField(default=1, help_text='Nombre max de comptes externes')),
                ('is_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expiré', 'Expiré'), ('résilié', 'Résilié')], db_index=True, default='actif', max_length=20)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('auto_renouvellement', models.BooleanField(default=True)),
                ('commercant', models.OneToOneField(limit_choices_to={'role': 'commercant'}, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'db_table': 'abonnements',
            },
        ),
    ]
