# Generated by Django 6.0.3 on 2026-05-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('nni', models.CharField(max_length=50)),
                ('nom_fr', models.CharField(blank=True, max_length=100)),
                ('nom_ar', models.CharField(blank=True, max_length=100)),
                ('prenom_fr', models.CharField(blank=True, max_length=100)),
                ('prenom_ar', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.CharField(blank=True, max_length=20)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(blank=True, max_length=10)),
                ('nationalite', models.CharField(blank=True, max_length=50)),
                ('face_verified', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('failed', 'Échoué')], db_index=True, default='verified', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enregistrement KYC',
                'db_table': 'kyc_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
